name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libjemalloc-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install jemalloc
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Run benchmarks
        run: make bench
