name: Swift

on:
  push:
    paths:
      - "Package.swift"
      - "**/*.swift"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            swift: "6.0"
            run-benchmarks: false
          - os: ubuntu-latest
            swift: "6.0"
            run-benchmarks: false
          - os: macos-latest
            swift: "6.1"
            run-benchmarks: true
          - os: ubuntu-latest
            swift: "6.1"
            run-benchmarks: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v6
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Run benchmarks
        if: matrix.run-benchmarks
        run: make bench
